services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: videoplanner
      POSTGRES_PASSWORD: videoplanner_dev
      POSTGRES_DB: videoplanner
    volumes:
      - videoplanner_pg:/var/lib/postgresql/data

volumes:
  videoplanner_pg:
