/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    productions: Production;
    categories: Category;
    'video-projects': VideoProject;
    notifications: Notification;
    media: Media;
    'shoot-setups': ShootSetup;
    'script-versions': ScriptVersion;
    'review-versions': ReviewVersion;
    'review-comments': ReviewComment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    productions: ProductionsSelect<false> | ProductionsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'video-projects': VideoProjectsSelect<false> | VideoProjectsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'shoot-setups': ShootSetupsSelect<false> | ShootSetupsSelect<true>;
    'script-versions': ScriptVersionsSelect<false> | ScriptVersionsSelect<true>;
    'review-versions': ReviewVersionsSelect<false> | ReviewVersionsSelect<true>;
    'review-comments': ReviewCommentsSelect<false> | ReviewCommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * שם התצוגה של המשתמש באפליקציה.
   * Display name in the app.
   */
  name: string;
  /**
   * קובע הרשאות: מנהל מערכת, מנהל פרויקט, עורך או מתמלל.
   * Controls permissions: admin, project manager, editor, or subtitler.
   */
  role: 'admin' | 'project_manager' | 'editor' | 'subtitler' | 'av_manager';
  /**
   * שליחת מייל כשמתרחש שינוי רלוונטי בפרק.
   * Send email when a relevant episode change occurs.
   */
  notifyByEmail?: boolean | null;
  /**
   * מקבל התראה על כל עדכון בפרק, בכל שדה.
   * Notify on every episode field update.
   */
  notifyOnAllChanges?: boolean | null;
  /**
   * שינויים בשדות עריכה: הערות, וימאו, קאפווינג.
   * Changes to editing fields: notes, Vimeo, Kapwing.
   */
  notifyOnEditing?: boolean | null;
  /**
   * שינויים בשדות תמלול: דגל תמלול, קישורי וימאו.
   * Changes to subtitling fields and Vimeo links.
   */
  notifyOnSubtitling?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productions".
 */
export interface Production {
  id: number;
  /**
   * שם ההצגה שמופיע בכותרת ובדף הבית.
   * Display name shown in the app header and overview.
   */
  name: string;
  /**
   * מזהה ייחודי לכתובת /productions/{slug}. אותיות לatin, מספרים ומקף בלבד.
   * Unique URL segment for /productions/{slug}. Latin letters, numbers, hyphens.
   */
  slug: string;
  /**
   * תיאור קצר של ההפקה (אופציונלי).
   * Optional short description of the production.
   */
  description?: string | null;
  /**
   * קוד HEX לתצוגה בלוח שנה, כרטיסים ותגיות.
   * HEX color for calendar, cards, and badges.
   */
  color?: string | null;
  /**
   * מספר לסידור ההפקות בדף הבית (נמוך = קודם).
   * Sort order on the home page (lower = first).
   */
  sortOrder?: number | null;
  /**
   * קישור לתיקיית Vimeo של ההפקה — מופיע בכותרת האפליקציה.
   * Production Vimeo folder link shown in the app top bar.
   */
  vimeoFolderUrl?: string | null;
  /**
   * קישור לפודקאסט Spotify של ההפקה.
   * Spotify podcast link for this production.
   */
  spotifyUrl?: string | null;
  /**
   * קישור לפלייליסט YouTube של ההפקה.
   * YouTube playlist link for this production.
   */
  youtubeUrl?: string | null;
  /**
   * משתמש שיוקצה אוטומטית לפרקים חדשים.
   * User auto-assigned as project manager on new episodes.
   */
  defaultProjectManager?: (number | null) | User;
  /**
   * עורך שיוקצה אוטומטית לפרקים חדשים.
   * Editor auto-assigned on new episodes.
   */
  defaultEditor?: (number | null) | User;
  /**
   * מתמלל שיוקצה אוטומטית לפרקים חדשים.
   * Subtitler auto-assigned on new episodes.
   */
  defaultSubtitler?: (number | null) | User;
  /**
   * שדות שיופיעו בטבלה, בדף פרטים ובטופס. ריק = כל השדות.
   * Fields shown in list, detail, and forms. Empty = all fields.
   */
  visibleEpisodeFields?:
    | (
        | 'status'
        | 'pipelineStage'
        | 'description'
        | 'requirements'
        | 'filmedAt'
        | 'driveFolderUrl'
        | 'shootSetup'
        | 'setupNotes'
        | 'shootToEditorNotes'
        | 'needsSubtitling'
        | 'vimeoBeforeSubtitling'
        | 'movedToKapwingArchive'
        | 'vimeoReadyFolderUrl'
        | 'editingShiftUpdate'
        | 'editingNotes'
        | 'publishedAt'
        | 'duration'
        | 'vimeoUrl'
        | 'vimeoFolderUrl'
        | 'spotifyUrl'
        | 'youtubeUrl'
        | 'short1Url'
        | 'short2Url'
        | 'short3Url'
        | 'audioUrl'
        | 'srtUrl'
        | 'projectManager'
        | 'editor'
        | 'subtitler'
        | 'wordpressPermalink'
      )[]
    | null;
  /**
   * שדות שמשתמשים (שאינם מנהלים) יוכלו לערוך. ריק = לפי תפקיד והקצאה.
   * Fields non-admin users may edit. Empty = role defaults apply.
   */
  editableEpisodeFields?:
    | (
        | 'status'
        | 'pipelineStage'
        | 'description'
        | 'requirements'
        | 'filmedAt'
        | 'driveFolderUrl'
        | 'shootSetup'
        | 'setupNotes'
        | 'shootToEditorNotes'
        | 'needsSubtitling'
        | 'vimeoBeforeSubtitling'
        | 'movedToKapwingArchive'
        | 'vimeoReadyFolderUrl'
        | 'editingShiftUpdate'
        | 'editingNotes'
        | 'publishedAt'
        | 'duration'
        | 'vimeoUrl'
        | 'vimeoFolderUrl'
        | 'spotifyUrl'
        | 'youtubeUrl'
        | 'short1Url'
        | 'short2Url'
        | 'short3Url'
        | 'audioUrl'
        | 'srtUrl'
        | 'projectManager'
        | 'editor'
        | 'subtitler'
        | 'wordpressPermalink'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * שם הקטגוריה לתצוגה.
   * Category display name.
   */
  name: string;
  /**
   * מזהה ייחודי לקטגוריה.
   * Unique category identifier.
   */
  slug: string;
  /**
   * קוד HEX לתצוגה בלוח שנה.
   * HEX color for calendar display.
   */
  color?: string | null;
  /**
   * סידור הקטגוריות ברשימות.
   * Sort order in category lists.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-projects".
 */
export interface VideoProject {
  id: number;
  /**
   * כל פרק שייך להפקה אחת.
   * Each episode belongs to one production.
   */
  production: number | Production;
  /**
   * מספר סידורי של הפרק בתוך ההפקה (ייחודי להפקה).
   * Sequential episode number within the production (unique per production).
   */
  episodeNumber?: number | null;
  /**
   * שם הפרק כפי שמוצג ברשימות ובדף הפרטים.
   * Episode title shown in lists and detail page.
   */
  title?: string | null;
  /**
   * מצב הפרק: עתידי, בתהליך או הסתיים.
   * Episode state: future, in progress, or completed.
   */
  status: 'future' | 'in_progress' | 'completed';
  /**
   * שלב בתהליך: תכנון, צילום, תמלול, עריכה, בדיקה, פרסום.
   * Workflow stage: planned, shoot, subtitling, editing, review, published.
   */
  pipelineStage: 'planned' | 'to_film' | 'filmed' | 'subtitling' | 'editing' | 'review' | 'published';
  /**
   * מנהל הפרויקט האחראי על הפרק.
   * Project manager responsible for this episode.
   */
  projectManager?: (number | null) | User;
  /**
   * עורך הווידאו המוקצה לפרק.
   * Video editor assigned to this episode.
   */
  editor?: (number | null) | User;
  /**
   * מתמלל המוקצה לפרק.
   * Subtitler assigned to this episode.
   */
  subtitler?: (number | null) | User;
  /**
   * תיאור תוכן הפרק.
   * Content description of the episode.
   */
  description?: string | null;
  /**
   * דרישות מיוחדות לצילום, עריכה או תמלול.
   * Special requirements for filming, editing, or subtitling.
   */
  requirements?: string | null;
  /**
   * תאריך הצילום.
   * Date the episode was filmed.
   */
  filmedAt?: string | null;
  /**
   * קישור לתיקיית Google Drive של הפרק.
   * Google Drive folder link for this episode.
   */
  driveFolderUrl?: string | null;
  /**
   * סטאפ סטנדרטי (למשל סטודיו תל אביב — כיסאות גבוהים).
   * Standard setup (e.g. Tel Aviv Studio — High Chairs).
   */
  shootSetup?: (number | null) | ShootSetup;
  /**
   * תוספת לסטאפ הסטנדרטי עבור הפרק הזה.
   * Extra setup notes for this episode.
   */
  setupNotes?: string | null;
  /**
   * מה ששמנו לב אליו בצילום וצריך להעביר לעורך.
   * What we noticed on set and need to pass to the editor.
   */
  shootToEditorNotes?: string | null;
  /**
   * תמונות נוספות לפרק זה.
   * Extra photos for this episode.
   */
  setupPhotos?: (number | Media)[] | null;
  /**
   * קטגוריה לתצוגה בלוח שנה.
   * Category for calendar display.
   */
  category?: (number | null) | Category;
  /**
   * סימון שהפרק דורש תמלול.
   * Flag that this episode needs subtitling.
   */
  needsSubtitling?: boolean | null;
  /**
   * הסרטון הועלה לוימאו לפני שלב התמלול.
   * Video uploaded to Vimeo before subtitling stage.
   */
  vimeoBeforeSubtitling?: boolean | null;
  /**
   * הקבצים הועברו לתיקיית ארכיון בקאפווינג.
   * Files moved to Kapwing archive folder.
   */
  movedToKapwingArchive?: boolean | null;
  /**
   * קישור לתיקיית Vimeo שבה כל הקבצים מוכנים.
   * Vimeo folder URL where all files are ready.
   */
  vimeoReadyFolderUrl?: string | null;
  /**
   * סיכום עדכון מהעורך אחרי משמרת.
   * Editor summary after an editing shift.
   */
  editingShiftUpdate?: string | null;
  /**
   * הערות כלליות לעריכה.
   * General editing notes.
   */
  editingNotes?: string | null;
  /**
   * תאריך הפרסום בפלטפורמות.
   * Publication date on platforms.
   */
  publishedAt?: string | null;
  /**
   * משך הפרק (למשל 45:30).
   * Episode duration (e.g. 45:30).
   */
  duration?: string | null;
  /**
   * קישור לפרק ב-Vimeo.
   * Link to the episode on Vimeo.
   */
  vimeoUrl?: string | null;
  /**
   * קישור לתיקיית Vimeo של הפרק.
   * Vimeo folder for this episode.
   */
  vimeoFolderUrl?: string | null;
  /**
   * קישור לפרק ב-Spotify.
   * Link to the episode on Spotify.
   */
  spotifyUrl?: string | null;
  /**
   * קישור לפרק ב-YouTube.
   * Link to the episode on YouTube.
   */
  youtubeUrl?: string | null;
  /**
   * קישור לשורט ראשון.
   * Link to short video #1.
   */
  short1Url?: string | null;
  /**
   * קישור לשורט שני.
   * Link to short video #2.
   */
  short2Url?: string | null;
  /**
   * קישור לשורט שלישי.
   * Link to short video #3.
   */
  short3Url?: string | null;
  /**
   * קישור לקובץ אודיו.
   * Link to audio file.
   */
  audioUrl?: string | null;
  /**
   * קישור לקובץ כתוביות SRT.
   * Link to SRT subtitle file.
   */
  srtUrl?: string | null;
  /**
   * מזהה ייבוא מ-Softr (לקריאה בלבד).
   * Softr import ID (read-only).
   */
  softrRecordId?: string | null;
  /**
   * קישור קבוע לפרק באתר WordPress.
   * Permanent link to the episode on WordPress.
   */
  wordpressPermalink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shoot-setups".
 */
export interface ShootSetup {
  id: number;
  /**
   * למשל: סטודיו תל אביב — כיסאות גבוהים, שני אנשים.
   */
  name: string;
  description?: string | null;
  photos?: (number | Media)[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  project?: (number | null) | VideoProject;
  type: 'status_change' | 'date_change' | 'assignment' | 'editing' | 'subtitling' | 'general';
  title: string;
  message: string;
  read?: boolean | null;
  emailSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "script-versions".
 */
export interface ScriptVersion {
  id: number;
  episode: number | VideoProject;
  version: number;
  label?: string | null;
  isCurrent?: boolean | null;
  createdBy?: (number | null) | User;
  scenes?:
    | {
        title: string;
        script?: string | null;
        visual?: string | null;
        duration?: string | null;
        images?: (number | Media)[] | null;
        shootSetup?: (number | null) | ShootSetup;
        sortOrder?: number | null;
        comments?:
          | {
              author?: (number | null) | User;
              body: string;
              createdAt?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-versions".
 */
export interface ReviewVersion {
  id: number;
  episode: number | VideoProject;
  version: number;
  label?: string | null;
  isCurrent?: boolean | null;
  videoUrl?: string | null;
  videoFile?: (number | null) | Media;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-comments".
 */
export interface ReviewComment {
  id: number;
  reviewVersion: number | ReviewVersion;
  author: number | User;
  body: string;
  timeSeconds: number;
  resolved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'productions';
        value: number | Production;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'video-projects';
        value: number | VideoProject;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'shoot-setups';
        value: number | ShootSetup;
      } | null)
    | ({
        relationTo: 'script-versions';
        value: number | ScriptVersion;
      } | null)
    | ({
        relationTo: 'review-versions';
        value: number | ReviewVersion;
      } | null)
    | ({
        relationTo: 'review-comments';
        value: number | ReviewComment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  notifyByEmail?: T;
  notifyOnAllChanges?: T;
  notifyOnEditing?: T;
  notifyOnSubtitling?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productions_select".
 */
export interface ProductionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  sortOrder?: T;
  vimeoFolderUrl?: T;
  spotifyUrl?: T;
  youtubeUrl?: T;
  defaultProjectManager?: T;
  defaultEditor?: T;
  defaultSubtitler?: T;
  visibleEpisodeFields?: T;
  editableEpisodeFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-projects_select".
 */
export interface VideoProjectsSelect<T extends boolean = true> {
  production?: T;
  episodeNumber?: T;
  title?: T;
  status?: T;
  pipelineStage?: T;
  projectManager?: T;
  editor?: T;
  subtitler?: T;
  description?: T;
  requirements?: T;
  filmedAt?: T;
  driveFolderUrl?: T;
  shootSetup?: T;
  setupNotes?: T;
  shootToEditorNotes?: T;
  setupPhotos?: T;
  category?: T;
  needsSubtitling?: T;
  vimeoBeforeSubtitling?: T;
  movedToKapwingArchive?: T;
  vimeoReadyFolderUrl?: T;
  editingShiftUpdate?: T;
  editingNotes?: T;
  publishedAt?: T;
  duration?: T;
  vimeoUrl?: T;
  vimeoFolderUrl?: T;
  spotifyUrl?: T;
  youtubeUrl?: T;
  short1Url?: T;
  short2Url?: T;
  short3Url?: T;
  audioUrl?: T;
  srtUrl?: T;
  softrRecordId?: T;
  wordpressPermalink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  project?: T;
  type?: T;
  title?: T;
  message?: T;
  read?: T;
  emailSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shoot-setups_select".
 */
export interface ShootSetupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  photos?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "script-versions_select".
 */
export interface ScriptVersionsSelect<T extends boolean = true> {
  episode?: T;
  version?: T;
  label?: T;
  isCurrent?: T;
  createdBy?: T;
  scenes?:
    | T
    | {
        title?: T;
        script?: T;
        visual?: T;
        duration?: T;
        images?: T;
        shootSetup?: T;
        sortOrder?: T;
        comments?:
          | T
          | {
              author?: T;
              body?: T;
              createdAt?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-versions_select".
 */
export interface ReviewVersionsSelect<T extends boolean = true> {
  episode?: T;
  version?: T;
  label?: T;
  isCurrent?: T;
  videoUrl?: T;
  videoFile?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-comments_select".
 */
export interface ReviewCommentsSelect<T extends boolean = true> {
  reviewVersion?: T;
  author?: T;
  body?: T;
  timeSeconds?: T;
  resolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * קישור ברירת מחדל לתיקיית Vimeo (אם אין קישור להפקה).
   * Default Vimeo folder when production has no link.
   */
  generalVimeoFolderUrl?: string | null;
  /**
   * קישור ברירת מחדל לפודקאסט.
   * Default Spotify podcast URL.
   */
  spotifyPodcastUrl?: string | null;
  /**
   * קישור ברירת מחדל לפלייליסט YouTube.
   * Default YouTube playlist URL.
   */
  youtubePlaylistUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  generalVimeoFolderUrl?: T;
  spotifyPodcastUrl?: T;
  youtubePlaylistUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}